apiVersion: v1
kind: PersistentVolume
metadata:
  name: bamboo-data
  # namespace: atlassian-bamboo
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/data/ajay
